### PR TITLE
Use markdown license for GPLv3.

### PR DESCRIPTION
**Pull request by iphydf**
---
This change is [Reviewable](https://reviewable.io/reviews/toktok/py-toxcore-c/11)

### CODE REVIEW

**Comment by GrayHatter** [comment]
I'm not okay with AGPLv3 for this repo, also, it's already GPL3, are you sure you can replace GPLv3 with AGPLv3?

**Comment by iphydf** [comment]
Yes, you can. Anyway, following yesterday's discussion about the implications of this license, I've decided to change it back to GPLv3 - still markdown though.

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/py-toxcore-c/11#-:-KaHHSwtwUKZjntTiqaS:b-jbsf8z)*

**Comment by piling** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/py-toxcore-c/11#-:-KaIh3AJuC4McausXrCp:b-jbsf8z)*

**Comment by fcore117** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/py-toxcore-c/11)*

**Pull request merged**
